# Default values
# -- Project promotion policies. More info [here](https://kargo.akuity.io/concepts#promotion-policies)
promotionPolicies: []
# promotionPolicies:
#   - autoPromotionEnabled: true
#     stage: dev
#   - autoPromotionEnabled: false
#     stage: staging
#   - autoPromotionEnabled: false
#     stage: production

# -- Project warehouses. More info [here](https://kargo.akuity.io/concepts#warehouse-resources)
warehouses: []
# warehouses:
#   - name: warehouse1
#     subscriptions:
#       - repoURL: ghcr.io/repo/image
#         semverConstraint: ^1.2.3
#       - repoURL: ghcr.io/repo/chart
#         semverConstraint: ^4.5.6
#   - name: warehouse1
#     subscriptions:
#       - repoURL: ghcr.io/repo/image
#         semverConstraint: ^1.2.3
#       - repoURL: ghcr.io/repo/chart
#         semverConstraint: ^4.5.6

# -- Project stages. More info [here](https://kargo.akuity.io/concepts#stage-resources)
stages: []
# stages:
#   - name: stage1
#     requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: warehouse1
#       sources:
#         direct: true
#   - name: stage2
#     requestedFreight:
#     - origin:
#         kind: Warehouse
#         name: warehouse1
#       sources:
#         direct: true

# -- Project secrets. More info [here](https://kargo.akuity.io/how-to-guides/managing-credentials#credentials-as-kubernetes-secret-resources)
secrets: []
# secrets:
#   - name: my-github-pat
#     type: git
#     data:
#       githubAppID: <app id>
#       githubAppPrivateKey: <base64-encoded private key>
#       githubAppInstallationID: <installation id>
#       repoURL: <repo url>
#       repoURLIsRegex: <true if repoURL is a pattern matching multiple repositories>
#   - name: my-helm-registry
#     type: helm
#     data:
#       repoURL: <repo url>
#       username: <username>
#       password: <password>
#       repoURLIsRegex: <true if repoURL is a pattern matching multiple repositories>
#   - name: my-oci-registry
#     type: image
#     data:
#       repoURL: <repo url>
#       username: <username>
#       password: <password>
#       repoURLIsRegex: <true if repoURL is a pattern matching multiple repositories>
