{{- range $index, $secret := .Values.secrets }}
{{- with $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $secret.name }}
  namespace: {{ $.Release.Name }}
  labels:
    kargo.akuity.io/cred-type: {{ $secret.type }}
{{- with $secret.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}


