{{- range $index, $stage := .Values.stages }}
{{- with $stage }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .Release.Name }}-{{ $stage.name }}
  namespace: {{ .Release.Name }}
spec:
  {{- with .requestedFreight }}
  requestedFreight:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
