{{- range $index, $stage := .Values.stages }}
{{- with $stage }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ include "kargo-project.fullname" $ }}-{{ $stage.name }}
  namespace: {{ include "kargo-project.fullname" $ }}
spec:
  {{- with .requestedFreight }}
  requestedFreight:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
