{{- range $index, $warehouse := .Values.warehouses }}
{{- with $warehouse }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ $.Release.Name }}-{{ $warehouse.name }}
  namespace: {{ $.Release.Name }}
spec:
  {{- with .subscriptions }}
  subscriptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
