name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.0

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: 3.11.0
          yamllint_version: 1.33.0
          yamale_version: 4.0.4

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs .)
          echo "changed=$changed" >> $GITHUB_OUTPUT

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed != ''
        run: ct lint --chart-dirs . --charts "${{ steps.list-changed.outputs.changed }}"
