name: Release Helm Charts

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  changed-files:
    name: Get changed files on helm charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get helm changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          dir_names: "true"
          dir_names_max_depth: "1"
          files_ignore: |
            .github/**
            .gitignore
            LICENSE
            README.md
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  release-helm-charts:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.matrix != '[]'}}
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Build Helm chart
        id: build-package
        working-directory: ${{ matrix.chart }}
        run: |
          file=$(helm package --dependency-update . | cut -d":" -f2 | tr -d '[:space:]')
          echo "file=\"${file}\"" >> "${GITHUB_OUTPUT}"
      - name: Helm login in GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io
      - name: Push Helm chart to GHCR
        run: |
          helm push ${{ steps.build-package.outputs.file }} oci://ghcr.io/${{ github.repository_owner }}/helm-charts
